#!/bin/sh
#
#   Copyright 2014 Jonathan M. Reid. See LICENSE.txt
#   Created by: Jon Reid, http://qualitycoding.org/
#   Source: https://github.com/jonreid/XcodeCoverage
#

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
echo ${DIR}
source ${DIR}/envcov.sh
remove_old_report()
{
    pushd ${BUILT_PRODUCTS_DIR}
    if [ -e lcov ]; then
        rm -r lcov
    fi
    popd
}

enter_lcov_dir()
{
    cd ${BUILT_PRODUCTS_DIR}
    mkdir lcov
    cd lcov
}

gather_coverage()
{
    LCOV --capture --derive-func-data -b "${SRCROOT}" -d "${OBJ_DIR}" -o ${LCOV_INFO}
}

exclude_data()
{
    LCOV --remove ${LCOV_INFO} "Applications/Xcode.app/*" -d "${OBJ_DIR}" -o ${LCOV_INFO}
    LCOV --remove ${LCOV_INFO} "main.m" -d "${OBJ_DIR}" -o ${LCOV_INFO}
# While I would love to test these, without a UI it is super hard, and not worth it.
    LCOV --remove ${LCOV_INFO} "CMSocialLoginViewController.h" -d "${OBJ_DIR}" -o ${LCOV_INFO}
    LCOV --remove ${LCOV_INFO} "CMSocialLoginViewController.m" -d "${OBJ_DIR}" -o ${LCOV_INFO}
# This is actually tested, but the Code Coverage doesn't recognize the header file has
# Been tested, so it shows up as 0%... and that won't do.
    LCOV --remove ${LCOV_INFO} "CMUserAccountResult.h" -d "${OBJ_DIR}" -o ${LCOV_INFO}

}

generate_report()
{
    "${LCOV_PATH}/genhtml" --output-directory . ${LCOV_INFO}
    open index.html
}

remove_old_report
enter_lcov_dir
gather_coverage
exclude_data
generate_report
